### ISSUE TITLE
 Error: Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.

### ISSUE THREAD

**Issue by HeikkiYlipaavalniemi** [standup75/cropme#37]
I have tested the script on localhost and our development server. I keep getting the following error when trying to send the blob:

 Error: Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.
    at Error (native)
    at http://local:8000/assets/javascripts/cropme/cropme.js:565:24
    at link.getCropPromise (http://local:8000/assets/javascripts/cropme/cropme.js:299:13)
    at k.link.scope.ok (http://local:8000/assets/javascripts/cropme/cropme.js:377:26)
    at eb.functionCall (http://ajax.googleapis.com/ajax/libs/angularjs/1.3.6/angular.min.js:197:502)
    at https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.12/angular-touch.min.js:12:197
    at k.$get.k.$eval (http://ajax.googleapis.com/ajax/libs/angularjs/1.3.6/angular.min.js:125:305)
    at k.$get.k.$apply (http://ajax.googleapis.com/ajax/libs/angularjs/1.3.6/angular.min.js:126:6)
    at HTMLButtonElement.<anonymous> (https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.12/angular-touch.min.js:12:179)
    at HTMLButtonElement.c (http://ajax.googleapis.com/ajax/libs/angularjs/1.3.6/angular.min.js:32:285)

This seems to come from this line in cropme.js:

dataURI = canvas.toDataURL(type);

What causes this?

**Comment by oscar-g** [comment]
https://github.com/HeikkiYlipaavalniemi, were you able to find the cause of this issue?

-OG

**Comment by jlstr** [comment]
@HeikkiYlipaavalniemi Could you please elaborate on what's the solution for this issue?

**Comment by standup75** [comment]
If you get this problem let me know where you get the image from. For information on tainted canvases: https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_enabled_image
